services:
  dev-db:
    container_name: apartment-dev-db
    image: postgres:14.18-bookworm
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres # default db
    ports:
      - "54321:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  smaila:
    container_name: apartment-smaila-dev
    image: ghcr.io/cactusbros/smaila:v0.2.2
    restart: unless-stopped
    env_file:
      - .smaila.env
    ports:
      - $HTTP_PORT:$HTTP_PORT

volumes:
  postgres_data:
    driver: local
